---
abstract: unknown
author:
  - 'Salvador Fandino <sfandino@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SFTP-Foreign-Backend-Net_SSH2
no_index:
  directory:
    - t
    - inc
requires:
  Net::SFTP::Foreign: 1.67
  Net::SSH2: 0.38
version: 0.07
